import { defineConfig } from "tsup";
import { preserveDirectivesPlugin } from "esbuild-plugin-preserve-directives";
import preserveDirectives from "rollup-plugin-preserve-directives";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    accordion: "src/components/Accordion/index.ts",
    ai: "src/components/AI/index.ts",
    alert: "src/components/Alert/index.ts",
    alertdialog: "src/components/AlertDialog/AlertDialog.tsx",
    avatar: "src/components/Avatar/index.ts",
    badge: "src/components/Badge/index.ts",
    bentogrid: "src/components/BentoGrid/BentoGrid.tsx",
    breadcrumb: "src/components/Breadcrumb/index.ts",
    button: "src/components/Button/index.ts",
    calendar: "src/components/Calendar/Calendar.tsx",
    card: "src/components/Card/index.ts",
    carousel: "src/components/Carousel/Carousel.tsx",
    chart: "src/components/Chart/Chart.tsx",
    checkbox: "src/components/Checkbox/index.ts",
    colorpicker: "src/components/ColorPicker/ColorPicker.tsx",

    command: "src/components/Command/Command.tsx",
    contextmenu: "src/components/ContextMenu/ContextMenu.tsx",
    drawer: "src/components/Drawer/Drawer.tsx",
    dropdown: "src/components/Dropdown/index.ts",
    fileuploader: "src/components/FileUploader/index.ts",
    form: "src/components/Form/Form.tsx",
    hovercard: "src/components/HoverCard/HoverCard.tsx",
    image: "src/components/Image/Image.tsx",
    imagecropper: "src/components/ImageCropper/index.ts",
    input: "src/components/Input/index.ts",
    kanbanboard: "src/components/KanbanBoard/index.ts",
    label: "src/components/Label/Label.tsx",
    list: "src/components/List/index.ts",
    markdownviewer: "src/components/MarkdownViewer/index.ts",
    masonrygrid: "src/components/MasonryGrid/index.ts",
    modal: "src/components/Modal/index.ts",
    motion: "src/components/Motion/index.ts",
    navigationmenu: "src/components/NavigationMenu/NavigationMenu.tsx",
    numberinput: "src/components/NumberInput/NumberInput.tsx",
    otpinput: "src/components/OtpInput/index.ts",
    pagination: "src/components/Pagination/index.ts",
    passwordinput: "src/components/PasswordInput/PasswordInput.tsx",
    popover: "src/components/Popover/Popover.tsx",
    progress: "src/components/Progress/index.ts",
    radio: "src/components/Radio/index.ts",
    radiogroup: "src/components/RadioGroup/RadioGroup.tsx",
    rating: "src/components/Rating/index.ts",
    resizable: "src/components/Resizable/Resizable.tsx",
    runoxprovider: "src/components/RunoxProvider/index.ts",
    scrollarea: "src/components/ScrollArea/ScrollArea.tsx",
    separator: "src/components/Separator/Separator.tsx",
    sidebar: "src/components/Sidebar/Sidebar.tsx",
    signaturepad: "src/components/SignaturePad/index.ts",
    skeleton: "src/components/Skeleton/index.ts",
    slider: "src/components/Slider/index.ts",
    sortablelist: "src/components/SortableList/index.ts",
    spinner: "src/components/Spinner/Spinner.tsx",
    stepper: "src/components/Stepper/index.ts",
    switch: "src/components/Switch/index.ts",
    syntaxhighlighter: "src/components/SyntaxHighlighter/index.ts",
    table: "src/components/Table/index.ts",
    tabs: "src/components/Tabs/index.ts",
    taginput: "src/components/TagInput/index.ts",
    textarea: "src/components/Textarea/index.ts",
    themeprovider: "src/components/ThemeProvider/index.ts",
    timeline: "src/components/Timeline/index.ts",
    toast: "src/components/Toast/index.ts",
    tooltip: "src/components/Tooltip/index.ts",
    treeview: "src/components/TreeView/index.ts",
    virtuallist: "src/components/VirtualList/index.ts",
  },
  format: ["cjs", "esm"],
  dts: true,
  splitting: true,
  treeshake: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
  minify: true,
  injectStyle: false,
  esbuildPlugins: [
    preserveDirectivesPlugin({
      directives: ["use client", "use strict"],
      include: /\.(js|ts|jsx|tsx)$/,
      exclude: /node_modules/,
    }),
  ],
  banner: {
    js: '"use client";\n/* runox ui */',
  },
  esbuildOptions(options) {
    options.conditions = [...(options.conditions || []), "style"];
  },
  onSuccess: "node scripts/postbuild.js",
});
