export const typography = {
  fontFamily: {
    sans: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
    heading: "'Outfit', var(--font-sans)",
    mono: "'Space Mono', ui-monospace, 'SF Mono', Menlo, Monaco, Consolas, monospace",
  },
  fontSize: {
    "2xs": ["0.625rem", { lineHeight: "0.875rem" }],
    xs: ["0.75rem", { lineHeight: "1rem" }],
    sm: ["0.8125rem", { lineHeight: "1.25rem" }],
    base: ["0.875rem", { lineHeight: "1.5rem" }],
    md: ["1rem", { lineHeight: "1.5rem" }],
    lg: ["1.125rem", { lineHeight: "1.75rem" }],
    xl: ["1.25rem", { lineHeight: "1.75rem" }],
    "2xl": ["1.5rem", { lineHeight: "2rem" }],
    "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
    "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
    "5xl": ["3rem", { lineHeight: "1.1" }],
    "6xl": ["3.75rem", { lineHeight: "1.1" }],
  },
  fontWeight: {
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
    extrabold: "800",
  },
  letterSpacing: {
    tighter: "-0.05em",
    tight: "-0.02em",
    normal: "0em",
    wide: "0.05em",
    wider: "0.1em",
    widest: "0.15em",
  },
} as const;
